(deftheme concrete "The concrete GRAY color theme")


(custom-theme-set-faces
 'concrete
 '(cursor ((t (:background "red"))))
 '(default ((t (:background "lightgray"))))
 '(fringe ((t (:background "lightgray"))))
 '(vertical-border ((t (:foreground "darkgray"))))
 '(mode-line-buffer-id ((t (:foreground "blue"))))
 '(line-number-current-line ((t (:foreground "red"))))
 '(font-lock-doc-face ((t (:foreground "firebrick" :slant italic))))
 '(font-lock-comment-face ((t (:foreground "gray40"))))
 '(magit-section-highlight ((t (:background "gray90"))))
 '(magit-diff-context-highlight ((t (:background "gray90"))))
 '(org-block ((t (:background "gray90"))))
 '(org-meta-line ((t (:foreground "black" :background "gray75"))))
 '(org-level-1 ((t (:foreground "purple"))))
 '(org-level-3 ((t (:foreground "blue"))))
 '(org-level-4 ((t (:foreground "darkgreen"))))
 '(org-level-5 ((t (:foreground "firebrick"))))
 '(font-lock-type-face ((t (:foreground "darkgreen" :weight bold))))
 '(clojure-keyword-face ((t (:foreground "darkgreen"))))
 '(cider-repl-stderr-face ((t (:foreground "firebrick" :weight bold))))
 '(cider-error-overlay-face ((t (:foreground "firebrick" :weight bold))))
 '(cider-result-overlay-face (()))
 '(eros-result-overlay-face (()))
 '(dired-subtree-depth-1-face ((t (:background "inherit"))))
 '(dired-subtree-depth-2-face ((t (:background "inherit"))))
 '(dired-subtree-depth-3-face ((t (:background "inherit"))))
 '(dired-subtree-depth-4-face ((t (:background "inherit"))))
 '(dired-subtree-depth-5-face ((t (:background "inherit"))))
 '(dired-subtree-depth-6-face ((t (:background "inherit")))))


(provide-theme 'concrete)
